name = "bmendoza-io"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-12-16"

[site]
bucket = "./public"

[build]
command = "pnpm run build"
