name: Code Quality Checks

on:
  pull_request: null
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  quality-checks:
    name: Run code quality checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: 'Setup Node.js, pnpm and dependencies'
        uses: ./.github/actions/setup-env

      - name: 'Run linting, formatting and type checks'
        uses: ./.github/actions/code-quality-checks
